services:
  laravel-testbench:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    working_dir: /app
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testbench
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

    volumes:
      - './db:/var/lib/mysql'
